// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rtc_services.proto
// Original file comments:
// The protocol buffer 3 interface definitions
#ifndef GRPC_rtc_5fservices_2eproto__INCLUDED
#define GRPC_rtc_5fservices_2eproto__INCLUDED

#include "rtc_services.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace mediaservice {

// The media rtc service definition.
class MediaRTC final {
 public:
  static constexpr char const* service_full_name() {
    return "mediaservice.MediaRTC";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Get the receive address for udp data
    virtual ::grpc::Status get_recv_address(::grpc::ClientContext* context, const ::mediaservice::RecvAddrRequest& request, ::mediaservice::RecvAddrResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mediaservice::RecvAddrResponse>> Asyncget_recv_address(::grpc::ClientContext* context, const ::mediaservice::RecvAddrRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mediaservice::RecvAddrResponse>>(Asyncget_recv_addressRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mediaservice::RecvAddrResponse>> PrepareAsyncget_recv_address(::grpc::ClientContext* context, const ::mediaservice::RecvAddrRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mediaservice::RecvAddrResponse>>(PrepareAsyncget_recv_addressRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Get the receive address for udp data
      virtual void get_recv_address(::grpc::ClientContext* context, const ::mediaservice::RecvAddrRequest* request, ::mediaservice::RecvAddrResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void get_recv_address(::grpc::ClientContext* context, const ::mediaservice::RecvAddrRequest* request, ::mediaservice::RecvAddrResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mediaservice::RecvAddrResponse>* Asyncget_recv_addressRaw(::grpc::ClientContext* context, const ::mediaservice::RecvAddrRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mediaservice::RecvAddrResponse>* PrepareAsyncget_recv_addressRaw(::grpc::ClientContext* context, const ::mediaservice::RecvAddrRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status get_recv_address(::grpc::ClientContext* context, const ::mediaservice::RecvAddrRequest& request, ::mediaservice::RecvAddrResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mediaservice::RecvAddrResponse>> Asyncget_recv_address(::grpc::ClientContext* context, const ::mediaservice::RecvAddrRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mediaservice::RecvAddrResponse>>(Asyncget_recv_addressRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mediaservice::RecvAddrResponse>> PrepareAsyncget_recv_address(::grpc::ClientContext* context, const ::mediaservice::RecvAddrRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mediaservice::RecvAddrResponse>>(PrepareAsyncget_recv_addressRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void get_recv_address(::grpc::ClientContext* context, const ::mediaservice::RecvAddrRequest* request, ::mediaservice::RecvAddrResponse* response, std::function<void(::grpc::Status)>) override;
      void get_recv_address(::grpc::ClientContext* context, const ::mediaservice::RecvAddrRequest* request, ::mediaservice::RecvAddrResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::mediaservice::RecvAddrResponse>* Asyncget_recv_addressRaw(::grpc::ClientContext* context, const ::mediaservice::RecvAddrRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::mediaservice::RecvAddrResponse>* PrepareAsyncget_recv_addressRaw(::grpc::ClientContext* context, const ::mediaservice::RecvAddrRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_get_recv_address_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Get the receive address for udp data
    virtual ::grpc::Status get_recv_address(::grpc::ServerContext* context, const ::mediaservice::RecvAddrRequest* request, ::mediaservice::RecvAddrResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_get_recv_address : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_get_recv_address() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_get_recv_address() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_recv_address(::grpc::ServerContext* /*context*/, const ::mediaservice::RecvAddrRequest* /*request*/, ::mediaservice::RecvAddrResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_recv_address(::grpc::ServerContext* context, ::mediaservice::RecvAddrRequest* request, ::grpc::ServerAsyncResponseWriter< ::mediaservice::RecvAddrResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_get_recv_address<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_get_recv_address : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_get_recv_address() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::mediaservice::RecvAddrRequest, ::mediaservice::RecvAddrResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::mediaservice::RecvAddrRequest* request, ::mediaservice::RecvAddrResponse* response) { return this->get_recv_address(context, request, response); }));}
    void SetMessageAllocatorFor_get_recv_address(
        ::grpc::MessageAllocator< ::mediaservice::RecvAddrRequest, ::mediaservice::RecvAddrResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::mediaservice::RecvAddrRequest, ::mediaservice::RecvAddrResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_get_recv_address() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_recv_address(::grpc::ServerContext* /*context*/, const ::mediaservice::RecvAddrRequest* /*request*/, ::mediaservice::RecvAddrResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* get_recv_address(
      ::grpc::CallbackServerContext* /*context*/, const ::mediaservice::RecvAddrRequest* /*request*/, ::mediaservice::RecvAddrResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_get_recv_address<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_get_recv_address : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_get_recv_address() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_get_recv_address() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_recv_address(::grpc::ServerContext* /*context*/, const ::mediaservice::RecvAddrRequest* /*request*/, ::mediaservice::RecvAddrResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_get_recv_address : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_get_recv_address() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_get_recv_address() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_recv_address(::grpc::ServerContext* /*context*/, const ::mediaservice::RecvAddrRequest* /*request*/, ::mediaservice::RecvAddrResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_recv_address(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_get_recv_address : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_get_recv_address() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->get_recv_address(context, request, response); }));
    }
    ~WithRawCallbackMethod_get_recv_address() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_recv_address(::grpc::ServerContext* /*context*/, const ::mediaservice::RecvAddrRequest* /*request*/, ::mediaservice::RecvAddrResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* get_recv_address(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_get_recv_address : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_get_recv_address() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::mediaservice::RecvAddrRequest, ::mediaservice::RecvAddrResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::mediaservice::RecvAddrRequest, ::mediaservice::RecvAddrResponse>* streamer) {
                       return this->Streamedget_recv_address(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_get_recv_address() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status get_recv_address(::grpc::ServerContext* /*context*/, const ::mediaservice::RecvAddrRequest* /*request*/, ::mediaservice::RecvAddrResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedget_recv_address(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::mediaservice::RecvAddrRequest,::mediaservice::RecvAddrResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_get_recv_address<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_get_recv_address<Service > StreamedService;
};

}  // namespace mediaservice


#endif  // GRPC_rtc_5fservices_2eproto__INCLUDED
